= Участие

Мы очень рады любым предложениям или участию в улучшении содержания. Цель этого репозитория — помочь сотрудникам Ярославского государственного университета им. П.Г. Демидова начать работу с Github-организацией.

== Как участвовать

=== Заявки на исправление ошибки (ишью)

Самый простой способ поучаствовать — отправить link:https://github.com/uniyar/getting-started/issues[заявку на исправление ошибки], комментируя текст, опечатки или предлагая улучшения и новые идеи.

=== Запросы на внесение изменений

Если ты знаком с git и пул реквестами (запросами на внесение изменений), можешь также такой запрос, где напрямую предлагаются изменения в контенте. Подробнее о том, как работают пул реквесты, можно прочитать link:https://app.egghead.io/playlists/how-to-contribute-to-an-open-source-project-on-github[здесь].

Вкратце:

1. Создай форк репозитория и клонируй его локально.
2. Создай новую ветку в своей локальной копии этого репозитория.
3. Сделай изменения в этой ветке.
4. Отправь эту ветку в свой форк этого репозитория на GitHub.
5. Отправь запрос на внесение изменений из этой ветки в основную ветку основного репозитория.
6. Если получишь отзывы, внеси изменения на локальном компьютере и повтори отправку на GitHub: запрос на внесение изменений обновится автоматически.