:profile_page: https://github.com/uniyar
:portal_link: https://portal.uniyar.ac.ru/
:register_link: https://portal.uniyar.ac.ru/company/personal/user/14486/
:github_registration_link: https://github.com/join
:github_security_link: https://github.com/settings/security
:github_2fa_cli_link: https://docs.github.com/ru/authentication/securing-your-account-with-two-factor-authentication-2fa/accessing-github-using-two-factor-authentication#using-two-factor-authentication-with-the-command-line

= Начало работы

Начнем с описания первых шагов по началу работы с link:{profile_page}[GitHub-организацией ЯрГУ]. GitHub-организацией — это общий аккаунт, в котором участники могут управлять своими проектами, используя свой личный аккаунт GitHub. GitHub-организацией Ярославского государственного университета им. П.Г. Демидова предназначена для хранения, управления и публикации исследовательских проектов. Ниже ты найдешь инструкции по подключению к организации и общие инструкции по её использованию. Внизу страницы приведены ресурсы по основам использования Git для контроля версий.

Описания лучших практик приведены по ссылке link:docs/best-practices.adoc[Лучшие практики по Git @uniyar].


== Подключение к организации GitHub

Членство в GitHub-организации Ярославского государственного университета им. П.Г. Демидова, включая доступ ко внутренним репозиториям, ограничено сотрудниками ЯрГУ. Чтобы стать членом, используй существующую личную учетную запись GitHub. если у тебя еще нет аккаунта, пожалуйста, создай его. Далее следует запросить доступ на link:{portal_link}[корпоративном портале], оставив сообщение для  link:{register_link}[указанного пользователя]. Вся деятельность в рамках GitHub-организации будет интегрирована в личный профиль GitHub (который можно рассматривать как своего рода резюме). Помимо вклада (работы) в GitHub-организации ЯрГУ там будут отображаться вклады и в другие
 организации GitHub или личные репозитории.

=== Быстрый старт

1. link:{github_registration_link}[Создай личный GitHub-аккаунт] (не нужно делать, если личный GitHub-аккаунт уже существует).
2. Зайди в личный GitHub-аккаунт.
3. link:{github_security_link}[Настрой двухфакторную аутентификацию для своей учетной записи GitHub].
4. *Присоединись к GitHub-организации ЯрГУ*, запросив доступ на link:{register_link}[корпоративном портале].
5. Дождись ответа от администратора.
6. Переходи на {profile_page} и приступай к работе!

=== Доступ из командной строки

Чтобы получить первоначальный доступ к GitHub-организации ЯрГУ, выполни описанные выше действия.

WARNING: После включения двухфакторной аутентификации для личного GitHub-аккаунта ты больше не сможешь подключаться к своим удалённым репозиториям, используя HTTPS-ссылки в сочетании с паролем от GitHub. Вместо этого тебе нужно будет настроить _SSH-ключ_ или _Персональный токен доступа_. Это действие выполняется один раз. После этого взаимодействие с GitHub будет таким же, как и раньше.

Используй _SSH-ключ_ или _Персональный токен доступа_ (Personal Access Token, PAT), чтобы получить доступ к своим ресурсам из командной строки, смотри link:{github_2fa_cli_link}[инструкции по использованию двухфакторной аутентификации с командной строкой]. Эти ключи должны быть авторизованы для использования в link:{profile_page}[GitHub-организации ЯрГУ]. При использовании SSH-ключа тебе нужно будет изменить URL-адреса удаленных репозиториев с HTTPS-схемы на SSH-схему. При использовании PAT (персонального токена доступа) можешь продолжать использовать HTTPS-ссылки. Вот инструкции:

* SSH доступ:
  . link:{https://docs.github.com/ru/authentication/connecting-to-github-with-ssh}[Создание SSH-ключа].
  . link:{https://docs.github.com/ru/enterprise-cloud@latest/authentication/authenticating-with-saml-single-sign-on/authorizing-an-ssh-key-for-use-with-saml-single-sign-on}[Авторизация SSH-ключа для использования в GitHub-организации ЯрГУ].
  . link:{https://docs.github.com/ru/get-started/getting-started-with-git/managing-remote-repositories?platform=windows}[Изменение URL-адресов всех существующих репозиториев с HTTPS на SSH].
* PAT доступ:
  . [Авторизация персонального токена доступа для использования в GitHub-организации ЯрГУ](https://docs.github.com/ru/enterprise-cloud@latest/authentication/authenticating-with-saml-single-sign-on/authorizing-a-personal-access-token-for-use-with-saml-single-sign-on)
  . [Персональный токен доступа и GitHub](https://happygitwithr.com/https-pat.html)

== Использование

=== Платформа для исследований и проектов ЯрГУ

Используй эту GitHub-организацию для исследовательских проектов или других работ, связанных с ЯрГУ. Не следует использовать эту организацию для учебных упражнений или личной деятельности.

=== Код и конфиденциальные данные

Эта GitHub-организация предназначена для управления исходным кодом. Не рекомендуется использовать GitHub для хранения наборов данных с личными или конфиденциальными данными. Однако для контроля версий документов или небольших обезличенных наборов данных её вполне можно использовать. При возникновении сомнений не мешкая link:{mailto:github@uniyar.ac.ru}[обращайся за советом к нам].

=== Ответственность

Будь в курсе общих университетских правил использования информационных систем и link:./docs/security-best-practices.md[лучших практик безопасности для GitHub].

Если вы новичок в Git, обязательно изучите link:#learning-git[основы управления версиями Git] для правильного управления своими проектами. Типичные угрозы включают *публикацию данных, которые не должны быть опубликованы, или публикацию паролей*. Убедись, что ты знаешь, как указать Git, какие файлы должны или не должны быть под контролем версий, особенно если работа связана с какими-либо конфиденциальными данными. Наконец, имей в виду, что если какие-либо сторонние приложения авторизованы на доступ к твоему аккаунту или к аккаунту кого-то из коллег, то эти приложения могут иметь доступ к данным в ваших частных репозиториях.

Изучи link:./docs/security-best-practices.md[советы по безопасности для GitHub].


=== GitHub Pages

Ты можешь использовать GitHub Pages для продвижения исследовательских проектов, например, публикуя веб-сайт проекта. Для целей дизайна можно использовать логотип ЯрГУ. Однако следует воздержаться от копирования дизайна, относящегося к корпоративному веб-сайту link:{https://uniyar.ac.ru}[университета].

=== Рекомендации по именованию репозиториев

Используй названия репозиториев, которые описывают проект. Не используй названия, которые могут быть какими-то двусмысленными, особенно когда они связаны с законом или политикой (например, названия репозиториев, содержащие `policy` или `terms`). Мы оставляем за собой право переименовывать репозитории с двусмысленными названиями. В случае сомнений link:https://github.com/uniyar/getting-started#contact[свяжись с нами].

=== Лицензирование и авторские материалы

Обязательно добавь лицензию к своей работе, поскольку она определяет правила для людей, которые хотят использовать твой код/программное обеспечение. Если ты используешь повторно лицензированное программное обеспечение, убедись, что выбранная тобой лицензия совместима с лицензией переиспользованного программного обеспечения. link:https://choosealicense.com/[Помощь в выборе лицензии].

== Ресурсы

=== Создание репозиториев

Как только ты попадешь в GitHub-организацию ЯрГУ, следуя описанным выше шагам, тебе будет предоставлено разрешение на создание репозиториев в организации. Изучи link:{https://docs.github.com/ru/github/creating-cloning-and-archiving-repositories/creating-a-new-repository}[документацию GitHub] для получения инструкций по созданию репозитория.

=== Создание команд

Создавай команды для управления репозиториями и формированием группы коллег, работающих над проектом. Сразу после попадании в GitHub-организацию ЯрГУ у тебя будет возможность создавать команды. Изучи link:{https://docs.github.com/ru/organizations/organizing-members-into-teams}[документацию GitHub] для получения инструкций по созданию команды. [Подробнее о том, как управлять командой в GitHub-организации ЯрГУ](docs/managing-your-team.md)

=== Приглашение коллег

После создания репозитория или команды ты автоматически получишь возможность добавлять участников. Когда ты link:https://docs.github.com/ru/organizations/organizing-members-into-teams/adding-organization-members-to-a-team[приглашаешь] человека в команду, он автоматически получает приглашение на вступление в GitHub-организацию ЯрГУ. Если ты хочешь пригласить коллегу в репозиторий без использования команд GitHub, коллега должен сначала стать членом GitHub-организации через описанные выше шаги. Если коллега является членом GitHub-организации ЯрГУ, ты можешь пригласить его для совместной работы над репозиториями.

=== Приглашение внешних партнеров

Ты можешь приглашать партнеров из сторонних организаций или студентов для совместной работы над репозиториями. Для этого добавь их в качестве внешних сотрудников (external collaborator) в репозитории: link:https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/adding-outside-collaborators-to-repositories-in-your-organization[см. документацию GitHub]. Будь ответственным при приглашении внешних сотрудников; приглашай их только в те репозитории, к которым им действительно нужен доступ.

=== Перенос существующего репозитория в эту GitHub-организацию

Возможно ты захочешь перенести существующий репозиторий в эту GitHub-организацию ЯрГУ. Для этого используй функцию link:https://docs.github.com/en/repositories/creating-and-managing-repositories/duplicating-a-repository[зеркалирования].

WARNING: *Не используй опцию* «Передать собственность» в настройках репозитория для перемещения репозитория в эту GitHub-организацию ЯрГУ. Так ты потеряешь административные права на репозиторий.


=== Ограничения на GitHub Actions

Минуты и пространство в сервисе GitHub Actions являются неограниченными для публичных репозиториев. Всегда, когда возможно, используй _публичные_ репозитории при работе с GitHub Actions. В GitHub Actions  на уровне организации существуют месячные лимиты ресурсов на использование в частных репозиториях. *Как только эта квота будет израсходована, минуты GitHub Actions будут отключены для частных репозиториев на оставшуюся часть месяца*.

== Изучение Git

Использование системы контроля версий Git является ключевым элементом в парадигме открытой науки и помогает управлять версиями файлов, налаживать сотрудничеством и публиковать свои результаты. Новичку в Git стоит уделить время для ознакомления с методами работы. Однодневный курс поможет тебе начать.

Ресурсы:

- https://youtu.be/O00FTZDxD0o?si=szTpW-TX2jD7WwTT[GIT - Полный Курс Git и GitHub Для Начинающих (4 ЧАСА)].
- link:docs/web-interface.md[Введение в графический интерфейс GitHub].
- link:https://skills.github.com[Интерактивные курсы по GitHub].
- link:docs/managing-your-team.md[Управление командой GitHub-организации ЯрГУ].

Курсы:
- https://www.uu.nl/en/research/research-data-management/training-workshops/best-practices-for-writing-reproducible-code[Best practices for writing reproducible code]

== Участие

Мы очень рады любым предложениям или исправлениям для улучшения контента. Цель этого репозитория — помочь сотрудникам Ярославского государственного университета им. П.Г. Демидова начать работу с GitHub-организацией ЯрГУ. Прочитай руководство по link:/CONTRIBUTING.md[участию].

== Лицензия

Содержание этого репозитория лицензировано в соответствии с link:{https://creativecommons.org/publicdomain/zero/1.0/deed.ru}[Creative Commons Zero 1.0] (передача в общественное достояние).

== Контактная информация

Тебе нужна помощь или у есть другие пожелания? link:{https://github.com/uniyar/getting-started/issues/new}[Создай ишью] (issue) или напиши по электронной почте link:{mailto:github@uniyar.ac.ru}[github@uniyar.ac.ru]. Мы также будем рады всем желающим внести вклад в этот репозиторий.