:toc2:

As a researcher you might be interested in this GitHub thing you have been hearing so much about.
This article outlines what benefits you might get in the short and long term, what challenges you may face, and what to expect from the adoption of GitHub.

Как исследователю тебе может быть интересно что это за штука `GitHub`, о которой столько разговоров вокруг. Эта статья описывает, какие выгоды ты можешь получить в короткой и долгой перспективе, с какими трудностями ты можешь столкнуться и что ожидать от использования `GitHub`.

== Что такое `GitHub`

Для понимания `GitHub` сначала нужно объяснить лежащую в его основе технологию системы контроля версий `git`. Что делает `git`, так это предоставляет способ сохранять файлы вместе информацией о версиях (отсюда и контроль версий). Представь, что ты работаешь с документом, и тебя есть две версии — до рецензирования и после:

* `статья_до_рецензирования.doc`
* `статья_после_рецензирования.doc`

Вместе с `git` ты можешь иметь один файл с именем `статья.doc`, но у него будет две версии: `до_рецензирования` и `после_рецензирования`. Система позволяет переключаться между версиями и работать с любой из них. Кроме того, каждое «сохранение» может быть снабжено дополнительной информацией (описанием) версии, чтобы было легче её отыскать в будущем. Кроме того, для текстовых файлов, вроде программного кода, `git` позволяет отыскивать точные места в файле, в которых были правки.

Система `git` работает локально, то есть прямо на твоём компьютере, это уже достаточно полезный инструмент. Суть в том, что `git` добавляет дополнительное измерение к тому, как хранятся файлы. Теперь они находятся не только в определённом месте на твоём компьютере, но и во времени.

Если говорить про `GitHub`, то это как бы `Dropbox` или `Яндекс.Диск` для файлов, которыми ты управляешь с помощью `git`.

То, что `git` делает локально, `GitHub` делает в облаке. То есть ты можешь загрузить файлы на `GitHub`, и они будут доступны в любом месте, где есть Интернет. Также можно поделиться своими файлами с другими людьми, чтобы они могли скачивать их или даже вносить изменения. Таким образом, `GitHub` позволяет совместно работать с другими людьми над одними и теми же файлами и разные люди могут создавать разные версии одного и того же файла, которые впоследствии можно объединить в один файл.

Например, ты можешь написать введение к статье и загрузить документ на `GitHub`. Твой коллега скачивает этот документ и  дополняет заготовку твоей статьи разделом «Методы», после чего выгружает новую версию документа на `GitHub`. После этого ты расширяешь введение, добавляя в него что-то из раздела «Методы», и, таким образом, создаешь новую версию документа. Таким образом, вы совместно работаете над одним и тем же документом, и каждый из вас в любой момент может скачать последнюю версию файла и продолжить работу над ним.

Такой способ работает относительно нормально с текстом, но особенно он хорош при работе с программным кодом. Представь, что твоя команда часто работает с неким устройством, которое генерирует CSV-файл с результатами эксперимента. Твой коллега создал скрипт, который интерпретирует данные и генерирует диаграмму размаха (aka «ящик с усами»). Но для твоего исследования требуется  линейная диаграмма. Вместо того, чтобы договариваться с коллегой и просить передать тебе скрипт для внесения изменений, ты забираешь его из репозитория на `GitHub`, расширяешь свои код своими модификациями для создания линейной диаграммы и затем снова выгружаешь его на `GitHub`, чтобы другие участники исследовательской команды могли тоже строить при необходимости линейные диаграммы.

Однако можно пойти дальше и поделиться своими файлами не только с коллегами по команде, но со всеми в мире. Твоя программа будет доступна _публично_, и разные люди из разных стран смогут скачивать её и использовать в своих исследованиях. Если популярность твоего инструмента будет расти, то вместе с ней будет расти и твоя репутацию в научном сообществе. Более того вклад в совместное улучшение программы смогут внести все желающие!

На опубликованный код можно будет ссылаться в статьях и публикациях, указывая конкретную версию в истории изменений, чтобы облегчить проверку результатов и повторное использование программы.

`GitHub` предоставляет множество других возможностей, которые будут (конечно не все) объяснены чуть позже в этом документе, но в своей основе `GitHub` — это место для хранения файлов в «облаке».

== С чего начать


`GitHub` и `git` обладают множеством функций, которые без сомнения улучшат твой рабочий процесс разными способами, но не все инвестиции времени одинаково окупаются.

Используя даже минимальный набор возможностей `git` и `GitHub`, ты получишь значительные выгоды. Под начальным освоением понимаются следующие шаги:

* [ ] Создай учетную запись на `GitHub`.
* [ ] Получи доступ в `GitHub`-организацию ЯрГУ.
* [ ] Скачай и установи приложение `GitHub Desktop`.
* [ ] Изредка выкладывай свой код на `GitHub` с помощью `GitHub Desktop`.

Выполнение этих действий потребует максимум 30 минут на первые три шага, и по 5 минут каждый раз, когда ты будешь выкладывать код на `GitHub`. За эти усилия ты получишь улучшение личного рабочего процесса, поможешь своим коллегам (команде), увеличишь свои влияние и репутацию в научном сообществе.

=== Выгода для тебя

Наиболее важным улучшением станет то, что у тебя будут **резервные копии** твоего кода. Храня его в облаке, ты всегда сможешь восстановить утраченный программный код. При чем не только самую последнюю версию, но и **каждую версию**, которая когда-либо была выгружена. Ты сможешь просматривать запомненные варианты и восстанавливать их в любое время.

Размещая свой код на `GitHub`, ты сможешь ссылаться на него в своих исследованиях. Помимо цитирования традиционных источников в научных статьях ты сможешь **ссылаться на свой `GitHub`-репозиторий**. А если ты найдешь на `GitHub` другое полезное для исследования программное обеспечение, то можно сослаться и на него!

Использование `GitHub` также поможет **найти полезное программное обеспечение** для твоего исследовательского проекта. Тебе не придется каждый раз «изобретать велосипед» и выяснять, как именно следует считывать данные из CSV-файла.

Подобно публикациям в научных журналах, **код тоже является публикацией**. Твой общедоступный код образует **портфолио**, которое можно демонстрировать потенциальным заказчикам, особенно если твои амбиции связаны с IT-сферой. Кроме того `GitHub` позволяет получать обратную связь — узнавать сколько людей заинтересовались и/или используют твое программное обеспечение. Это хорошая мотивация для дальнейшей разработки, чтобы программное обеспечение стало более полезным и для тебя, и для твоих коллег-исследователей.

=== Выгода для коллектива

Поскольку ты размещаешь программный код на `GitHub`, твои **коллеги могут легко получить доступ к нему** без необходимости обмениваться кодом через флешки, почту или непредназначенные для работы с кодом сервисы. Не стоит забывать, что другие пользователи кода смогут вносить в него изменения, чтобы сделать программу еще лучше и удобнее в использовании.

С другой стороны, если ты работаешь в команде и твой напарник решил сменить место работы, то **ваша программа не исчезает** вместе с ним.

Помимо прочего `GitHub` позволяет систематизировано отслеживать ошибки и указывать на недостающие возможности программы, чтобы вы вместе с командой могли их учитывать при постепенном развитии кода.

=== Выгода для научного сообщества

Публикуя программный код на `GitHub`, ты вносишь вклад в инструментарий научного сообщества в целом. Ты *предоставляешь строительные блоки* для других исследователей, способствуя проведению более качественных и надежных исследований. Более того, ты улучшаешь свою *репутацию*, следуя стандартам `Open Science` и `FAIR`. Открывая такой *публичный интерфейс* к своей работе, ты «приглашаешь» незнакомых людей вносить улучшения в программный код и в твои научные изыскания. Размещение программного кода в `GitHub-организации` ЯрГУ приведёт к тому, что твоя работа будет более заметной (по крайней мере среди тех, кто интересуется разработками ЯрГУ). Публикуя программный код на `GitHub`, ты также значительно упрощаешь процесс воспроизведения и проверки научных результатов, что в долгосрочной перспективе приведёт к *повышению качества исследований*.

== Углубленные возможности

Чем больше возможностей `GitHub` ты используешь, тем больше будут и выгоды.

Общепризнанной модели использования `GitHub` в публикации научных результатов и средств их получения не существует, поэтому мы можем лишь предполагать какие долгосрочные преимущества можно получить, адаптируя подходы из области профессиональной разработки программного обеспечения.

Обобщив опыт других учёныхfootnote:[https://marciovm.com/i-want-a-github-of-science] footnote:[https://marciovm.com/i-want-a-github-of-science] footnote:[https://peerj.com/preprints/3159v2/] и указанные наработки, мы можем сделать следующие предположения:


* Применяя `GitHub Actions` можно автоматически запускать код каждый раз, когда что-то на `GitHub` меняется:
  ** публиковать препринты с каждой новой версией в качестве формы динамической публикации,
  ** проверять и тестировать программное обеспечение с каждой новой версией и оценивать, не нарушает ли новая версия старую функциональность,
  ** использовать искусственный интеллект (ИИ) для оценки публикуемого кода, и получать рекомендации по его улучшению.
* Используя `GitHub Issues` можно отслеживать будущее развитие программного обеспечения или другого создаваемого контента:
  ** создавать списки задач для разных членов команды,
  ** внешние пользователи могут сообщать о найденных ошибках и проблемах,
  ** запрашивать новые функции для стороннего программного обеспечения.
* Используя `GitHub Pull Requests` можно проводить рецензирование программного кода:
  ** отслеживать не весь код, а только предлагаемые изменения,
  ** учитывать все комментарии и предложения,
* Используя `devcontainers` можно создавать виртуальные рабочие пространства, которые позволят тебе работать с `GitHub` независимо от конфигурации твоего компьютера.
* Используя `GitHub Discussions` можно выстраивать сотрудничество внутри и вне команды в формате длинных текстовых сообщений.
* Благодаря открытости программного кода, ты сможешь создавать все более полезные и удобные возможности, сотрудничая с коллегами по всему миру.
* Количество цитирований твоих научных публикаций будет расти вместе с количеством `GitHub`-публикаций.

В целом, качество научных исследований повысится из-за того, что все материалы находятся в открытом доступе.
В мире индустриальной разработки открытость — проверенная концепция, обладающая огромной движущей силой в создании высококачественного программного обеспечения.

== Распространенные заблуждения, опасения и проблемы

Этот раздел призван развеять распространенные аргументы против использования `GitHub`.

В зависимости от уровня понимания программирования, знакомства с кодом и других нетехнических факторов, у тебя могут быть сомнения по поводу использования `GitHub`.
Если эти опасения не нашли (полного) отражения в этом разделе, мы предлагаем тебе link:https://github.com/uniyar/getting-started/issues/new[открыть тему (issue)] в этом репозитории, объяснив сомнения подробнее, чтобы мы могли расширить этот раздел.

=== Мой код не достаточно хорош, чтобы быть публичным

Если твой код достаточно хорош, чтобы делать на его основе научные выводы, то он достаточно хорош для того, чтобы быть опубликованным.
Можно даже утверждать, что именно этом случае он прямо таки требует, чтобы его опубликовали.
В общем и целом, плохой код все же лучше, чем никакой.
В отличии от правил редакционных комитетов, твой код не должен соответствовать определенным стандартам качества (пока что).
Огромное количество низкокачественного программного кода с ошибками и без документации ежедневно используется во всем мире, пока это ПО приносит пользу и делает то, что должно, оно будет «в ходу» независимо от качества.
В твоём случае код должен воспроизводить результаты исследования на исходных данных, это и есть критерий качества.
Пока он делает это, он идеален.
Все остальное — всего лишь дополнительные понты .

=== Люди будут указывать на ошибки в моем коде

Это верно, но стоит ли этого бояться? Наоборот надо это приветствовать.
Ошибки в коде могут означать, что выводы исследования неверны.
Чем раньше они будут обнаружены, тем лучше.

Может возникнуть опасение, что ты будешь вынужден отзывать свои исследования из-за ошибок, и это действительно вполне реальный риск. Однако самоотзыв не вредит репутацииfootnote:[https://journals.sagepub.com/doi/pdf/10.1177/2515245918776632] и даже может её улучшить. В отличие от подлога.


=== Компания X не позволит мне

Компании могут оказывать некоторое влияние на публикацию данных, но в большинстве случаев им не важно, какие инструменты используются для обработки данных.
При использовании `GitHub`, в первую очередь речь идет о коде, а не о данных.
Даже если компания настаивает на том, чтобы код был закрытым, ты все равно можешь использовать `GitHub`.
Можно установить видимость репозитория с кодом на `private` (частный) и получать все преимущества работы с кодом внутри команды в закрытом режиме.

=== Это очень сложно для меня

Безусловно, тебе придется потратить некоторое время на изучение инструментов `git` и `GitHub`.
В зависимости от уровня технической подготовки это может быть легче или сложнее.
В любом случае, вложенные усилия всегда окупаются.
В современном технологическом ландшафте существует множество инструментов, которые облегчают работу с `GitHub`.
Кроме того, в сети есть множество ресурсов, которые помогут изучить `GitHub` разными способами, от инструкций и видеоуроков до обучающих работе с `git` видеоигр.

=== У меня нет времени учиться

Сэкономленное время от регулярного переизобретения программного кода каждые несколько месяцев, гораздо больше времени, которое тебе придется потратить на освоение базовых возможностей `GitHub`.
Уже само наличие централизованного места для программного кода внутри команды позволит сэкономить много времени — не придется делиться архивами с программным кодом через чаты и/или электронную почту.
Всё это без учёта времени, которое ты выиграешь от постепенного улучшения своего программного обеспечения на протяжении многих недель, месяцев и лет.

=== Никто так не делает

Действительно не так много учебных и научных заведений используют `GitHub` для публикации научных результатов. Однако их все больше и больше.
Например, Стэнфордский университет опубликовал открытые версии Alpaca.
Кроме того, если ты хочешь продолжать работать в том же традиционном режиме еще 100 лет, то это само по себе проблема.
Взглянув на сообщество открытого программного обеспечения, можно обнаружть множество примеров эффективной в инновациях открытости. Как исследователь, ты должен, хотя бы попробовать это.

=== У меня нет времени поддерживать код

Никто не имеет права требовать технической поддержки для свободно предоставляемого кода: если обратная связь бесполезена, игнорируй её.

== Как начать

Лучший способ начать — это как можно быстрее выложить какой-нибудь свой программный код на `GitHub`.
Для этого нужно перейти link:https://github.com/uniyar/getting-started[по ссылке и следовать инструкциям] по созданию учетной записи, загрузке `GitHub Desktop` и присоединению к организации ЯрГУ.

Затем выбери какой-нибудь актуальный свой программный код и выложи его на `GitHub`.

И вот — официальное начало положено.

С этого момента ты можешь начать исследовать в интерфейс `GitHub`. Вот ресурсы, которые помогут начать:
- [Краткое описание интерфейса](web-interface.md).
- [Как создать команду в `GitHub` и управлять ею](managing-your-team.md)

== Дополнительные ресурсы

- https://docs.github.com/ru/desktop[Документация GitHub Desktop]
- https://tom.preston-werner.com/2009/05/19/the-git-parable.html[Object Model]
- https://ohmygit.org/[Git-игра]
- https://docs.github.com/en/get-started/quickstart/set-up-git[Туториал по командной строке]
- https://guides.github.com/activities/hello-world/[Hello World]
