== Лучшие практики безопасности в GitHub

При использовании системы контроля версий на онлайн-платформах, таких как GitHub, важно знать о рисках безопасности.
Если проект состоит из нескольких скриптов для анализа табличных данных, то риски обычно невелики, и для обеспечения безопасности требуются минимальные усилия.
При увеличении сложности проектов (например, при работе с конфиденциальными данными или настройке автоматизированных конвейеров обработки), требуется большее внимание к безопасности.

Ниже приведен список лучших практик безопасного создания программного кода. Они условно разделены на категории:

* *начальный уровень* (отдельные скрипты, нечувствительные данные),
* *средний уровень* (чувствительные данные, конвейеры обработки данных) и
* *продвинутый уровень* (разработка программного обеспечения высокого качества).

=== Общие рекомендации

- https://www.kaspersky.ru/resource-center/threats/how-to-create-a-strong-password[Выбрать надежный пароль] (*начальный уровень*)
- https://docs.github.com/ru/github/authenticating-to-github/securing-your-account-with-two-factor-authentication-2fa[Защитить аккаунт GitHub с помощью двухфакторной аутентификации (2FA)] (*начальный уровень*)

=== Лучшие практики

- Используй `.gitignore`-файл чтобы в `GitHub`-репозиторий не попадали лишние данные, в том числе секреты/пароли, внешние зависимости и файлы локальных  конфигурации (*начальный уровень*)
- Регулярно проверяй права доступа членов ваших репозиториев (например, удаляйте неактивных участников) (*начальный уровень*)
- Поддерживай актуальность внешних зависимостей программного обеспечения (*средний уровень*)
- Создай для своего репозитория https://docs.github.com/ru/code-security/getting-started/adding-a-security-policy-to-your-repository[файл с политикой безопасности] `SECURITY.md` (*средний уровень*, если применимо)
- Изучи и применяй Github-конвенции (например, для использования веток, именования веток и сообщений о коммитах) (*средний уровень*)
- Изучи и используй руководства и соглашениям по стилю кодирования (*средний/продвинутый уровень*)
- Знай о методах безопасного кодирования (*средний/продвинутый уровень*)

== Дальнейшее изучение

- https://spectralops.io/blog/8-top-git-security-issues-what-to-do-about-them/[8 главных проблем безопасности Git и как с ними быть] (англ.)
- https://learn.microsoft.com/ru-ru/training/modules/maintain-secure-repository-github/[Онлайн курс по безопасности в Github] (1 час)